[package]
name = "example2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.4"
hound = "3.4.0"
multiqueue = "0.3.2"
eframe = "0.16.0"